name: docker ci

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: build docker image
      run: docker build . -t github-container

    - name: log into ghcr.io
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: push image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository }}
        IMAGE_NAME=$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]')
        docker tag github-container $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest
